---
- name: Copy /etc/logrotate.conf
  copy:
    src: "{{ role_path }}/files/logrotate_logrotate.conf"
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644
- name: Copy /etc/logrotate.d/rsyslog
  copy:
    src: "{{ role_path }}/files/logrotate_rsyslog"
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: 0644
- name: Force -f option with '/usr/sbin/logrotate /etc/logrotate.conf' in /etc/cron.daily/logrotate
  lineinfile:
    path: /etc/cron.daily/logrotate
    regexp: '(/usr/sbin/logrotate) (/etc/logrotate.conf)'
    line: '\1 -f \2'
    state: present
    backrefs: yes
