---
# main.yml
- include_tasks: rsyslog.yml
- include_tasks: logrotate.yml
- include_tasks: motd.yml
- include_tasks: systemd-resolved.yml

- name: Set timezone to "{{ containers_timezone }}"
  timezone:
    name: "{{ containers_timezone }}"

- name: Copy /root/.bashrc
  copy:
    src: "{{ role_path }}/files/main_.bashrc"
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644

- name: Copy /root/.vimrc
  copy:
    src: "{{ role_path }}/files/main_.vimrc"
    dest: /root/.vimrc
    owner: root
    group: root
    mode: 0644

- include_tasks: apt.yml
