---
containers_config:
    limits.cpu: "2"
    limits.memory: "2GB"
    boot.autostart: "true"

containers_source:
    type: "image"
    mode: "pull"
    server: "https://images.linuxcontainers.org"
    protocol: "simplestreams"
    alias: "ubuntu/bionic/amd64"

# * The container_interface name can't include the '-' symbol
# * The DNS IPs are set per interface and not globally, which sounds logic
# as the DNS server has to be accessed via a specific netwotk
networks:
    - name: "external"
      host_bridge: "br-ext"
      container_interface: "eth_ext"
      cidr_ip: 192.168.1.0/24
      gateway: 192.168.1.1
      gateway_is_default_route: True
      dns_ip: []
    - name: "internal"
      host_bridge: "br-int"
      container_interface: "eth_int"
      cidr_ip: 10.10.0.0/24
      gateway:
      gateway_is_default_route: False
      dns_ip:
        - 10.10.0.31 # We use here the internal IP of the DNS container

# The network names must match those declared in previous 'networks' section
containers:
    dns_hosts:
        ubudns02:
            external: 192.168.1.231
            internal: 10.10.0.31
    dhcp_hosts:
        ubudhcp02:
            external: 192.168.1.232
            internal: 10.10.0.32

# The SSH public key, added in the /root/.ssh/authorized_keys file into the containers
ansible_ssh_public_key: "/root/.ssh/id_rsa.pub"
# The network ansible uses to connect to the containers
ansible_network: "internal"
# The python path in containers for ansible
ansible_python_interpreter: '/usr/bin/env python3'
# The timezone for containers
containers_timezone: 'Europe/Paris'


dns_domain_external: "grimal-fr.com"
dns_domain_internal: "grimal-fr.home"
