---
containers_config:
    limits.cpu: "2"
    limits.memory: "2GB"
    boot.autostart: "true"

containers_source:
    type: "image"
    mode: "pull"
    server: "https://images.linuxcontainers.org"
    protocol: "simplestreams"
    alias: "ubuntu/bionic/amd64"

networks:
    - name: "external"
      host_bridge: "br-ext"
      container_interface: "ethext"
      cidr_ip: 192.168.1.0/24
      gateway: &gateway 192.168.1.1
      default_route: True
      dns_access: True
    - name: "internal"
      host_bridge: "br-int"
      container_interface: "ethint"
      cidr_ip: 10.10.0.0/25

containers:
    dns_hosts:
        ubudns02:
            external: &dns_external_ip 192.168.1.231
            internal: &dns_internal_ip 10.10.0.31
    dhcp_hosts:
        ubudhcp02:
            external: 192.168.1.232
            internal: 10.10.0.32

dns_first_ip: *dns_internal_ip
dns_second_ip: *gateway
dns_domain_external: "grimal-fr.com"
dns_domain_internal: "grimal-fr.home"
