network:
    ethernets:
        {% for network, param_dict in network_config.items() -%}
        {% if network in container_config -%}
        {{ param_dict['container_interface'] }}:
            dhcp4: no
            dhcp6: no
            addresses: [{%- for network_name, ip in container_config.items() -%}
                            {%- if network == network_name -%}
                                {{ ip }}
                            {%- endif -%}
                        {%- endfor -%}]
            {% if 'gateway' in param_dict -%}
            gateway4: {{ param_dict['gateway'] }}
            {% endif -%}
            {% if 'default_route' in param_dict -%}
            routes:
                - to: 0.0.0.0/0
                  via: {{ param_dict['gateway'] }}
            {% endif -%}
            {% if 'dns_access' in param_dict -%}
            nameservers:
                addresses: [{{ dns_first_ip }},{{ dns_second_ip }}]
            {% endif -%}
        {% endif %}
        {% endfor -%}
