---
- name: Update repositories cache and install base packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
      - apt-utils
      - bash-completion
      - dnsutils
      - htop
      - iftop
      - man-db
      - curl
      - tcpdump
      - mlocate
      - net-tools
      - openssh-server
