---
- name: Copy /etc/rsyslog.conf
  copy:
    src: "{{ role_path }}/files/rsyslog_rsyslog.conf"
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  register: rsyslog_conf_task

- name: Copy /etc/rsyslog.d/50-default.conf
  copy:
    src: "{{ role_path }}/files/rsyslog_50-default.conf"
    dest: /etc/rsyslog.d/50-default.conf
    owner: root
    group: root
    mode: 0644
  register: rsyslog_default_conf_task

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  when:
  - rsyslog_conf_task.changed or
    rsyslog_default_conf_task.changed
