---
# role certificate_authority - file main.yml
- name: Update repositories cache and install "easy-rsa" package
  apt:
    name: easy-rsa
    update_cache: yes
    state: present

- name: Copy /usr/share/easy-rsa in /etc
  command: cp -r /usr/share/easy-rsa /etc/

- name: Create directory "keys" in /etc/easy-rsa
  file:
    path: /etc/easy-rsa/keys
    state: directory
    mode: 0700
