---
# Copyright (c) 2018 Aurélien Grimal
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- include_tasks: rsyslog.yml
- include_tasks: logrotate.yml
- include_tasks: timezone.yml
- include_tasks: motd.yml
- include_tasks: systemd-resolved.yml
- name: Copy /etc/logrotate.conf
  copy:
    src: "{{ role_path }}/files/logrotate_logrotate.conf"
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644
- name: Copy /etc/logrotate.d/rsyslog
  copy:
    src: "{{ role_path }}/files/logrotate_rsyslog"
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: 0644
- name: Force -f option with '/usr/sbin/logrotate /etc/logrotate.conf' in /etc/cron.daily/logrotate
  lineinfile:
    path: /etc/cron.daily/logrotate
    regexp: '(/usr/sbin/logrotate) (/etc/logrotate.conf)'
    line: '\1 -f \2'
    state: present
    backrefs: yes
