---
- name: Copy "/etc/rsyslog.d/01-dhcpd.conf"
  copy:
    src: "{{ role_path }}/files/main_01-dhcpd.conf"
    dest: /etc/rsyslog.d/01-dhcpd.conf
    owner: root
    group: root
    mode: 0644
  register: copy_rsyslog_dhcpd_conf_task

- name: Verify that "/var/log/dhcpd" directory exists
  file:
    path: /var/log/dhcpd
    state: directory
    owner: syslog
    group: syslog
    mode: 0755

- name: Restart rsyslog service
  systemd:
    name: rsyslog
    state: restarted
  when:
    - copy_rsyslog_dhcpd_conf_task.changed
